name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y autoconf automake libtool
    - name: Generate configure script
      run: autoreconf --install || ./autogen.sh
    - name: Configure
      run: ./configure
    - name: Make
      run: make
    - name: Make check
      run: make check
    - name: Make distcheck
      run: make distcheck
